Repository Vanessa219/vditor, pull requests merged in 2020-07, with the labels that each got.

#571 feat: 增加预览工具条可配置且可自定义
  src/ts/preview/index.ts
  src/ts/util/Options.ts
  types/index.d.ts
Labels: 引入特性

#573 style: 优化分隔符样式
  src/assets/scss/_toolbar.scss
  src/assets/scss/index.scss
Labels: 改进功能

#582 修正单词拼写错误
  README.md
Labels: 文档相关

#616 fix: safari下选中文字添加标题文字会消失
  src/ts/ir/process.ts
Labels: 修复缺陷
